[theme]
base = "light"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false